"""Run from the repository root to regenerate the local browser country catalog."""
import json
from pathlib import Path

from core.countries import COUNTRIES


if __name__ == "__main__":
    target = Path(__file__).resolve().parents[1] / "frontend/public/country-data.js"
    target.write_text(
        "// Generated by backend/export_countries.py using pycountry; do not edit.\n"
        + "const COUNTRY_OPTIONS = " + json.dumps(COUNTRIES, ensure_ascii=False, separators=(",", ":")) + ";\n",
        encoding="utf-8",
        newline="\n",
    )
