-- Run after reviews.sql. Replies can target either a review or another reply
-- on that review, and are removed automatically with their parent review.
create table if not exists public.review_replies (
  id bigint generated by default as identity primary key,
  review_id bigint not null references public.reviews(id) on delete cascade,
  parent_reply_id bigint references public.review_replies(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  comment text not null check (char_length(btrim(comment)) between 1 and 2000),
  created_at timestamptz not null default now()
);

create index if not exists review_replies_review_id_created_at_idx
  on public.review_replies (review_id, created_at);

create index if not exists review_replies_parent_reply_id_idx
  on public.review_replies (parent_reply_id);

create or replace function public.validate_review_reply_parent()
returns trigger
language plpgsql
as $$
begin
  if new.parent_reply_id is not null and not exists (
    select 1
    from public.review_replies parent
    where parent.id = new.parent_reply_id
      and parent.review_id = new.review_id
  ) then
    raise exception 'A reply can only target another reply on the same review';
  end if;
  return new;
end;
$$;

drop trigger if exists review_replies_validate_parent on public.review_replies;
create trigger review_replies_validate_parent
before insert or update of review_id, parent_reply_id on public.review_replies
for each row execute function public.validate_review_reply_parent();

alter table public.review_replies enable row level security;

drop policy if exists "Review replies are public" on public.review_replies;
create policy "Review replies are public"
  on public.review_replies for select
  using (true);

drop policy if exists "Users can create their own review replies" on public.review_replies;
create policy "Users can create their own review replies"
  on public.review_replies for insert
  with check (auth.uid() = user_id);
