-- Run after reviews.sql. Replies can target either a review or another reply
-- on that review, and are removed automatically with their parent review.
create table if not exists public.review_replies (
  id bigint generated by default as identity primary key,
  review_id bigint not null references public.reviews(id) on delete cascade,
  parent_reply_id bigint references public.review_replies(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  comment text not null check (char_length(btrim(comment)) between 1 and 2000),
  created_at timestamptz not null default now()
);

alter table public.review_replies
  add column if not exists updated_at timestamptz not null default now();

create index if not exists review_replies_review_id_created_at_idx
  on public.review_replies (review_id, created_at);

create index if not exists review_replies_parent_reply_id_idx
  on public.review_replies (parent_reply_id);

create or replace function public.validate_review_reply_parent()
returns trigger
language plpgsql
as $$
begin
  if new.parent_reply_id is not null and not exists (
    select 1
    from public.review_replies parent
    where parent.id = new.parent_reply_id
      and parent.review_id = new.review_id
  ) then
    raise exception 'A reply can only target another reply on the same review';
  end if;
  return new;
end;
$$;

drop trigger if exists review_replies_validate_parent on public.review_replies;
create trigger review_replies_validate_parent
before insert or update of review_id, parent_reply_id on public.review_replies
for each row execute function public.validate_review_reply_parent();

create or replace function public.set_review_reply_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists review_replies_set_updated_at on public.review_replies;
create trigger review_replies_set_updated_at
before update on public.review_replies
for each row execute function public.set_review_reply_updated_at();

alter table public.review_replies enable row level security;

drop policy if exists "Review replies are public" on public.review_replies;
create policy "Review replies are public"
  on public.review_replies for select
  using (true);

drop policy if exists "Users can create their own review replies" on public.review_replies;
create policy "Users can create their own review replies"
  on public.review_replies for insert
  with check (auth.uid() = user_id);

drop policy if exists "Users can update their own review replies" on public.review_replies;
create policy "Users can update their own review replies"
  on public.review_replies for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "Users can delete their own review replies" on public.review_replies;
create policy "Users can delete their own review replies"
  on public.review_replies for delete
  using (auth.uid() = user_id);

create table if not exists public.review_reply_likes (
  id bigint generated by default as identity primary key,
  reply_id bigint not null references public.review_replies(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  constraint review_reply_likes_one_per_user unique (reply_id, user_id)
);

create index if not exists review_reply_likes_reply_id_idx
  on public.review_reply_likes (reply_id);

alter table public.review_reply_likes enable row level security;

drop policy if exists "Review reply likes are public" on public.review_reply_likes;
create policy "Review reply likes are public"
  on public.review_reply_likes for select using (true);

drop policy if exists "Users can like replies" on public.review_reply_likes;
create policy "Users can like replies"
  on public.review_reply_likes for insert with check (auth.uid() = user_id);

drop policy if exists "Users can remove their reply likes" on public.review_reply_likes;
create policy "Users can remove their reply likes"
  on public.review_reply_likes for delete using (auth.uid() = user_id);
