IN_HOUSE_GENRES = [
  "Action",
  "Adventure",
  "Comedy",
  "Crime",
  "Drama",
  "Dystopian",
  "Eastern",
  "Fantasy",
  "Historical",
  "Horror",
  "LGBTQ+",
  "LitRPG",
  "Mystery",
  "Paranormal",
  "Post-Apocalyptic",
  "Romance",
  "Sci-Fi",
  "Science Fiction",
  "Slice of Life",
  "Sports",
  "Supernatural",
  "Superhero",
  "Thriller",
  "Western",
  "Young Adult",
  "Cultivation",
  "Progression Fantasy",
  "Fanfiction",
  "Nonfiction",
  "Poetry",
  "Short Stories"
]